### ISSUE TITLE
Nodes don't stay synced on new chain

### ISSUE THREAD

**Issue by affiliatepayday** [wavesplatform/Waves#3576] opened 2021-11-08 05:08 UTC
Latest fork, nodes still desync from each other and don't stay synced and earning. 

Increasing the rollback to something like 40,000 or 50,000 helps some but not everyone. 

Logs have been shared in the last bug report that you guys ignored entirely after we left logs. 

I suspect you guys did something to your code intentionally so others couldn't fork it while your long withstanding chain stays working. So its probably more like a feature to you guys to prevent forking, but then you shouldn't leave broken code on github. 

Would be nice to get some insight on this.

**Comment by phearnot** [comment] 2021-11-10 12:28
Closing as a duplicate of #3538

**Closed as completed by phearnot** 2021-11-10 12:28 UTC
Labels: bug
