### ISSUE TITLE
InterruptedException

### ISSUE THREAD

**Issue by br0x** [wavesplatform/Waves#2883] opened 2020-01-20 13:33 UTC
Node version 1.1.7 brings a lot of messages like these:
```
INFO  c.w.s.BlockchainUpdaterImpl - MicroBlock(4AMiUqx... -> 5Z9x1kL..., txs=6) appended
INFO  c.w.s.BlockchainUpdaterImpl - MicroBlock(63CXony... -> 4AMiUqx..., txs=7) appended
java.lang.InterruptedException
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:998)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
        at java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.lockInterruptibly(ReentrantReadWriteLock.java:772)
        at com.wavesplatform.state.BlockchainUpdaterImpl.filledVolumeAndFee(BlockchainUpdaterImpl.scala:47)
        at com.wavesplatform.state.diffs.ExchangeTransactionDiff$.enoughVolume(ExchangeTransactionDiff.scala:128)
        at com.wavesplatform.state.diffs.ExchangeTransactionDiff$.$anonfun$apply$19(ExchangeTransactionDiff.scala:50)
        at com.wavesplatform.state.diffs.ExchangeTransactionDiff$.$anonfun$apply$16(ExchangeTransactionDiff.scala:45)
        at com.wavesplatform.state.diffs.ExchangeTransactionDiff$.$anonfun$apply$12(ExchangeTransactionDiff.scala:39)
        at com.wavesplatform.state.diffs.ExchangeTransactionDiff$.$anonfun$apply$8(ExchangeTransactionDiff.scala:33)
        at com.wavesplatform.state.diffs.ExchangeTransactionDiff$.apply(ExchangeTransactionDiff.scala:31)
        at com.wavesplatform.state.diffs.TransactionDiffer$.$anonfun$unverified$1(TransactionDiffer.scala:74)
        at com.wavesplatform.state.diffs.TransactionDiffer$.unverified(TransactionDiffer.scala:69)
        at com.wavesplatform.state.diffs.TransactionDiffer$.$anonfun$verified$9(TransactionDiffer.scala:56)
        at com.wavesplatform.state.diffs.TransactionDiffer$.$anonfun$verified$1(TransactionDiffer.scala:43)
        at com.wavesplatform.state.diffs.TransactionDiffer$.verified(TransactionDiffer.scala:42)
        at com.wavesplatform.state.diffs.TransactionDiffer$.$anonfun$apply$1(TransactionDiffer.scala:32)
        at com.wavesplatform.state.diffs.TransactionDiffer$.apply(TransactionDiffer.scala:34)
        at com.wavesplatform.utx.UtxPoolImpl.com$wavesplatform$utx$UtxPoolImpl$$addTransaction(UtxPoolImpl.scala:177)
        at com.wavesplatform.utx.UtxPoolImpl.$anonfun$putNewTx$13(UtxPoolImpl.scala:156)
        at com.wavesplatform.utx.UtxPoolImpl.putNewTx(UtxPoolImpl.scala:156)
        at com.wavesplatform.utx.UtxPoolImpl.putIfNew(UtxPoolImpl.scala:65)
        at com.wavesplatform.network.UtxPoolSynchronizer$.$anonfun$apply$1(UtxPoolSynchronizer.scala:100)
        at com.wavesplatform.network.UtxPoolSynchronizerImpl.$anonfun$validateFuture$1(UtxPoolSynchronizer.scala:77)
        at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
        at scala.util.Success.$anonfun$map$1(Try.scala:255)
        at scala.util.Success.map(Try.scala:213)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at monix.execution.internal.InterceptRunnable.run(InterceptRunnable.scala:27)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at com.wavesplatform.utils.Schedulers$TimedWrapper.run(Schedulers.scala:93)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
java.lang.InterruptedException
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1302)
        at java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.lockInterruptibly(ReentrantReadWriteLock.java:772)
        at com.wavesplatform.state.BlockchainUpdaterImpl.hasScript(BlockchainUpdaterImpl.scala:47)
        at com.wavesplatform.state.diffs.DiffsCommon$.$anonfun$countScriptRuns$2(DiffsCommon.scala:49)
        at com.wavesplatform.state.diffs.DiffsCommon$.$anonfun$countScriptRuns$2$adapted(DiffsCommon.scala:49)
        at scala.collection.TraversableOnce.$anonfun$count$1(TraversableOnce.scala:119)
        at scala.collection.TraversableOnce.$anonfun$count$1$adapted(TraversableOnce.scala:118)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at scala.collection.TraversableOnce.count(TraversableOnce.scala:118)
        at scala.collection.TraversableOnce.count$(TraversableOnce.scala:116)
        at scala.collection.AbstractTraversable.count(Traversable.scala:108)
        at com.wavesplatform.state.diffs.DiffsCommon$.countScriptRuns(DiffsCommon.scala:49)
        at com.wavesplatform.state.diffs.LeaseTransactionsDiff$.$anonfun$leaseCancel$6(LeaseTransactionsDiff.scala:78)
        at com.wavesplatform.state.diffs.LeaseTransactionsDiff$.$anonfun$leaseCancel$5(LeaseTransactionsDiff.scala:59)
        at com.wavesplatform.state.diffs.LeaseTransactionsDiff$.$anonfun$leaseCancel$3(LeaseTransactionsDiff.scala:55)
        at com.wavesplatform.state.diffs.LeaseTransactionsDiff$.$anonfun$leaseCancel$1(LeaseTransactionsDiff.scala:53)
        at com.wavesplatform.state.diffs.LeaseTransactionsDiff$.leaseCancel(LeaseTransactionsDiff.scala:52)
        at com.wavesplatform.state.diffs.TransactionDiffer$.unverifiedWithEstimate(TransactionDiffer.scala:98)
        at com.wavesplatform.state.diffs.TransactionDiffer$.$anonfun$unverified$1(TransactionDiffer.scala:76)
        at com.wavesplatform.state.diffs.TransactionDiffer$.unverified(TransactionDiffer.scala:69)
        at com.wavesplatform.state.diffs.TransactionDiffer$.$anonfun$verified$9(TransactionDiffer.scala:56)
        at com.wavesplatform.state.diffs.TransactionDiffer$.$anonfun$verified$1(TransactionDiffer.scala:43)
        at com.wavesplatform.state.diffs.TransactionDiffer$.verified(TransactionDiffer.scala:42)
        at com.wavesplatform.state.diffs.TransactionDiffer$.$anonfun$apply$1(TransactionDiffer.scala:32)
        at com.wavesplatform.state.diffs.TransactionDiffer$.apply(TransactionDiffer.scala:34)
        at com.wavesplatform.utx.UtxPoolImpl.com$wavesplatform$utx$UtxPoolImpl$$addTransaction(UtxPoolImpl.scala:177)
        at com.wavesplatform.utx.UtxPoolImpl.$anonfun$putNewTx$13(UtxPoolImpl.scala:156)
        at com.wavesplatform.utx.UtxPoolImpl.putNewTx(UtxPoolImpl.scala:156)
        at com.wavesplatform.utx.UtxPoolImpl.putIfNew(UtxPoolImpl.scala:65)
        at com.wavesplatform.network.UtxPoolSynchronizer$.$anonfun$apply$1(UtxPoolSynchronizer.scala:100)
        at com.wavesplatform.network.UtxPoolSynchronizerImpl.$anonfun$validateFuture$1(UtxPoolSynchronizer.scala:77)
        at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
        at scala.util.Success.$anonfun$map$1(Try.scala:255)
        at scala.util.Success.map(Try.scala:213)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at monix.execution.internal.InterceptRunnable.run(InterceptRunnable.scala:27)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at com.wavesplatform.utils.Schedulers$TimedWrapper.run(Schedulers.scala:93)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
INFO  c.w.s.BlockchainUpdaterImpl - MicroBlock(3PEs2Gi... -> 63CXony..., txs=4) appended

java.lang.InterruptedException
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:998)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
        at java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.lockInterruptibly(ReentrantReadWriteLock.java:772)
        at com.wavesplatform.state.BlockchainUpdaterImpl.accountData(BlockchainUpdaterImpl.scala:47)
        at com.wavesplatform.transaction.smart.WavesEnvironment.$anonfun$data$2(WavesEnvironment.scala:56)
        at com.wavesplatform.transaction.smart.WavesEnvironment.data(WavesEnvironment.scala:44)
        at com.wavesplatform.transaction.smart.WavesEnvironment.data(WavesEnvironment.scala:22)
        at com.wavesplatform.lang.v1.evaluator.ctx.impl.EnvironmentFunctions.$anonfun$getData$7(EnvironmentFunctions.scala:34)
        at com.wavesplatform.lang.v1.evaluator.ctx.impl.EnvironmentFunctions.getData(EnvironmentFunctions.scala:34)
        at com.wavesplatform.lang.v1.evaluator.ctx.impl.waves.Functions$$anon$1.apply(Functions.scala:39)
        at com.wavesplatform.lang.v1.evaluator.ctx.NativeFunction.eval(NativeFunction.scala:43)
        at com.wavesplatform.lang.v1.evaluator.EvaluatorV1.$anonfun$evalFunctionCall$9(EvaluatorV1.scala:100)
        at com.wavesplatform.lang.v1.task.TaskMT.$anonfun$flatMap$2(TaskMT.scala:38)
        at cats.Eval$.loop$1(Eval.scala:363)
        at cats.Eval$.cats$Eval$$evaluate(Eval.scala:368)
        at cats.Eval$FlatMap.value(Eval.scala:307)
        at com.wavesplatform.lang.v1.evaluator.EvaluatorV1.evalWithLogging(EvaluatorV1.scala:159)
        at com.wavesplatform.lang.v1.evaluator.ContractEvaluator$.apply(ContractEvaluator.scala:90)
        at com.wavesplatform.state.diffs.InvokeScriptTransactionDiff$.$anonfun$apply$10(InvokeScriptTransactionDiff.scala:91)
        at com.wavesplatform.state.diffs.InvokeScriptTransactionDiff$.$anonfun$apply$8(InvokeScriptTransactionDiff.scala:79)
        at com.wavesplatform.state.diffs.InvokeScriptTransactionDiff$.$anonfun$apply$2(InvokeScriptTransactionDiff.scala:78)
        at com.wavesplatform.state.diffs.InvokeScriptTransactionDiff$.apply(InvokeScriptTransactionDiff.scala:57)
        at com.wavesplatform.state.diffs.TransactionDiffer$.$anonfun$unverified$1(TransactionDiffer.scala:73)
        at com.wavesplatform.state.diffs.TransactionDiffer$.unverified(TransactionDiffer.scala:69)
        at com.wavesplatform.state.diffs.TransactionDiffer$.$anonfun$verified$9(TransactionDiffer.scala:56)
        at com.wavesplatform.state.diffs.TransactionDiffer$.$anonfun$verified$1(TransactionDiffer.scala:43)
        at com.wavesplatform.state.diffs.TransactionDiffer$.verified(TransactionDiffer.scala:42)
        at com.wavesplatform.state.diffs.TransactionDiffer$.$anonfun$apply$1(TransactionDiffer.scala:32)
        at com.wavesplatform.state.diffs.TransactionDiffer$.apply(TransactionDiffer.scala:34)
        at com.wavesplatform.utx.UtxPoolImpl.com$wavesplatform$utx$UtxPoolImpl$$addTransaction(UtxPoolImpl.scala:177)
        at com.wavesplatform.utx.UtxPoolImpl.$anonfun$putNewTx$13(UtxPoolImpl.scala:156)
        at com.wavesplatform.utx.UtxPoolImpl.putNewTx(UtxPoolImpl.scala:156)
        at com.wavesplatform.utx.UtxPoolImpl.putIfNew(UtxPoolImpl.scala:65)
        at com.wavesplatform.network.UtxPoolSynchronizer$.$anonfun$apply$1(UtxPoolSynchronizer.scala:100)
        at com.wavesplatform.network.UtxPoolSynchronizerImpl.$anonfun$validateFuture$1(UtxPoolSynchronizer.scala:77)
        at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
        at scala.util.Success.$anonfun$map$1(Try.scala:255)
        at scala.util.Success.map(Try.scala:213)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at monix.execution.internal.InterceptRunnable.run(InterceptRunnable.scala:27)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at com.wavesplatform.utils.Schedulers$TimedWrapper.run(Schedulers.scala:93)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by phearnot** [comment] 2020-02-03 09:00
Transaction validatiion interruption is not an issue in itself, the issue is in the way this exception spills to stdout. We've changed the way `InterruptedException`s are handled in #2885: they are now logged with `TRACE` level. This fix will be released with 1.1.8.

**Closed by phearnot** 2020-02-03 09:00 UTC
Labels: bug
