### ISSUE TITLE
walletSeed is interpreted incorrectly.

### ISSUE THREAD

**Issue by bcdev-** [wavesplatform/Waves#41] opened 2016-09-24 15:25 UTC
"walletSeed" is interpreted as Base58. This is incorrect. It should be interpreted in exactly the same way as in the webwallet.
For example:

```
"walletSeed": 4g7jtUbVJ1vpvJynsP8ZphQEt9R8eoQvbqGMzpuFmhAzSyu5kFgT7fDi92hEi1NCnzJ1M3CDLMVGvxcFZXoNXxN9
node: 3MuuBsiZjAkWETNNgY3JdQ7shy1Az8aEQ4Q
testnet.waveswallet.io: 3MySMuhh6QeN3Uejafd37WiEoZqg4PtieHb
```

Node should try to forge with the same address as a wallet created from that seed. Currently this is not the case.

**Comment by marilyn4325** [comment] 2016-09-24 21:36
duplicate of this issue which I reported some time ago:
https://github.com/wavesplatform/WavesGUI/issues/57

**Comment by bcdev-** [comment] 2016-09-24 21:46
Yep, it's kind of a duplicate. :-)
However, we differ in proposed solutions. You proposed to change .js part and do if(base58).
I propose to change the node part and scrap debase58ing altogether.

**Comment by Tolsi** [comment] 2016-11-28 11:40
We do not expect do this in the near future. I'll close this issue

**Closed by Tolsi** 2016-11-28 11:40 UTC
